name: Live Spider
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 16 * * *'

jobs:
  Spider:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    permissions:
      contents: write
    steps:
      - name: Clone TVSpider Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Upgrade Pip
        run: |
          python -m pip install --upgrade pip

      - name: Install requirements
        run: |
          pip install -r ./requirements.txt

      - name: Live Spider
        run: |
          python ./main.py

      - name: Commit Live Config files
        run: |
          git config --global user.email "github‑action@example.com"
          git config --global user.name "GitHub Action"
          git add json
          git add live
          # 仅检测 json live 目录变更，忽略log、缓存等其他文件
          CHANGED=$(git status --porcelain json live)
          if [[ -n "$CHANGED" ]];then
            git commit -m "* 更新直播源"
          else
            echo "json/live目录无变化，跳过提交"
          fi

      - name: Push Live Config Changes To Github
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ github.token }}
          directory: .
          branch: main
          force: false
